#!/usr/bin/env python3
"""
Train the convenience-store near-expiry supply forecaster.

We don't have real per-store reported-supply history, so we *simulate* a
plausible ground-truth process and train a logistic-regression model to recover
it. The point is the full ML pipeline (synthesise -> featurise -> train ->
evaluate -> export), and a model whose weights ship to the browser for
client-side inference (sigmoid over ~8 coefficients).

Ground-truth story: a store is more likely to have discounted near-expiry food
- in two daily windows: late morning (~11:00) and late evening (~21:30),
- a bit more in the evening and on weekends (more fresh stock to clear),
- with per-store variation (size / foot traffic) and chain effects.

Run:  python3 ml/train_forecast.py
Output: src/data/forecastModel.ts  (coefficients consumed by supplyForecast.ts)
"""
import json
import math
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, brier_score_loss

RNG = np.random.default_rng(42)
N = 12000

# ---- 1. Synthesise raw observations -----------------------------------------
hour = RNG.uniform(7, 24, N)               # store-open hours 07:00-24:00
is_weekend = RNG.integers(0, 2, N)         # 0 weekday, 1 weekend
chain = RNG.integers(0, 2, N)              # 0 = 7-ELEVEN, 1 = FamilyMart
traffic = RNG.uniform(0, 1, N)            # per-store foot-traffic proxy


def latent_prob(hour, is_weekend, chain, traffic):
    """The 'true' (hidden) probability the simulated world uses to draw labels."""
    morning = np.exp(-((hour - 11.0) ** 2) / (2 * 1.5 ** 2))
    evening = np.exp(-((hour - 21.5) ** 2) / (2 * 1.7 ** 2))
    base = np.maximum(morning, 1.15 * evening)        # evening peak slightly higher
    p = 0.06 + 0.8 * base
    p += 0.10 * is_weekend * evening                  # weekend evenings clear more
    p += 0.05 * (chain == 0)                          # 7-11 marginally more SKUs
    p += 0.12 * (traffic - 0.5)                       # busier stores cycle stock faster
    return np.clip(p, 0.02, 0.98)


p_true = latent_prob(hour, is_weekend, chain, traffic)
label = (RNG.uniform(0, 1, N) < p_true).astype(int)   # noisy Bernoulli draws


# ---- 2. Featurise (cyclical hour so 23:00 ~ 00:00 are close) ----------------
def featurise(hour, is_weekend, chain, traffic):
    ang = 2 * math.pi * hour / 24.0
    return np.column_stack([
        np.sin(ang), np.cos(ang),                     # 1st-harmonic time-of-day
        np.sin(2 * ang), np.cos(2 * ang),             # 2nd-harmonic (two daily peaks)
        is_weekend,
        chain,
        traffic,
    ])


FEATURES = ["sin_h", "cos_h", "sin_2h", "cos_2h", "is_weekend", "chain", "traffic"]
X = featurise(hour, is_weekend, chain, traffic)
y = label

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.25, random_state=0)

# ---- 3. Train ----------------------------------------------------------------
clf = LogisticRegression(max_iter=2000, C=2.0)
clf.fit(Xtr, ytr)

# ---- 4. Evaluate -------------------------------------------------------------
proba = clf.predict_proba(Xte)[:, 1]
auc = roc_auc_score(yte, proba)
acc = accuracy_score(yte, (proba >= 0.5).astype(int))
brier = brier_score_loss(yte, proba)

print("=" * 56)
print(f"  samples: {N}  (train {len(ytr)} / test {len(yte)})")
print(f"  positive rate: {y.mean():.3f}")
print(f"  ROC-AUC : {auc:.4f}")
print(f"  accuracy: {acc:.4f}")
print(f"  Brier   : {brier:.4f}  (lower = better calibrated)")
print("  coefficients:")
for name, w in zip(FEATURES, clf.coef_[0]):
    print(f"    {name:>10}: {w:+.4f}")
print(f"    {'bias':>10}: {clf.intercept_[0]:+.4f}")
print("=" * 56)

# ---- 5. Export for the browser ----------------------------------------------
model = {
    "features": FEATURES,
    "weights": [round(float(w), 6) for w in clf.coef_[0]],
    "bias": round(float(clf.intercept_[0]), 6),
    "metrics": {"auc": round(float(auc), 4), "acc": round(float(acc), 4),
                "brier": round(float(brier), 4), "n": int(N)},
}

out = Path(__file__).resolve().parent.parent / "src" / "data" / "forecastModel.ts"
ts = (
    "// AUTO-GENERATED by ml/train_forecast.py — do not edit by hand.\n"
    "// Logistic-regression weights for the convenience-store near-expiry\n"
    "// supply forecaster. Trained offline on synthetic data; inference runs\n"
    "// client-side in src/lib/supplyForecast.ts.\n"
    f"// Test ROC-AUC {model['metrics']['auc']} · accuracy {model['metrics']['acc']} "
    f"· Brier {model['metrics']['brier']} · n={model['metrics']['n']}.\n\n"
    "export interface ForecastModel {\n"
    "  features: string[];\n"
    "  weights: number[];\n"
    "  bias: number;\n"
    "  metrics: { auc: number; acc: number; brier: number; n: number };\n"
    "}\n\n"
    f"export const FORECAST_MODEL: ForecastModel = {json.dumps(model, ensure_ascii=False, indent=2)};\n"
)
out.write_text(ts, encoding="utf-8")
print(f"wrote {out}")
