// AUTO-GENERATED by ml/train_forecast.py — do not edit by hand.
// Logistic-regression weights for the convenience-store near-expiry
// supply forecaster. Trained offline on synthetic data; inference runs
// client-side in src/lib/supplyForecast.ts.
// Test ROC-AUC 0.8498 · accuracy 0.7683 · Brier 0.1572 · n=12000.

export interface ForecastModel {
  features: string[];
  weights: number[];
  bias: number;
  metrics: { auc: number; acc: number; brier: number; n: number };
}

export const FORECAST_MODEL: ForecastModel = {
  "features": [
    "sin_h",
    "cos_h",
    "sin_2h",
    "cos_2h",
    "is_weekend",
    "chain",
    "traffic"
  ],
  "weights": [
    -2.135116,
    -0.592027,
    -2.661745,
    1.956008,
    0.150555,
    -0.267362,
    0.72173
  ],
  "bias": -1.930026,
  "metrics": {
    "auc": 0.8498,
    "acc": 0.7683,
    "brier": 0.1572,
    "n": 12000
  }
};
